### ISSUE TITLE
Library does not have support for all API methods - such as finding a task

### ISSUE THREAD

**Issue by herdsothom** [mergentlabs/mergent-js#120]
Hi there,

In my use case I need to be able to use the [list/search tasks](https://api.mergent.co/docs#/paths/~1tasks/get) API to first check if a task has already been created with the same timestamp, before i create a new one.

It would be good if this module supported that, otherwise I need to manually call the API in which case this library becomes redundant anyway.

**Comment by jamescmartinez** [comment]
Hey @herdsothom! Apologies for the delay.

I'm currently toying with a way to generate (most of) this library from our OpenAPI spec. As soon as that's done, most likely, within the next week or so, I'll push an update that includes all of the API endpoints.

**Comment by jamescmartinez** [comment]
This was implemented in ba6911ff14bb5a5b37a078c0f94a63152b8716ae and released in 1.2.0. 🎊
