### ISSUE TITLE
[Feature Request] Manual Task Invocation

### ISSUE THREAD

**Issue by jgtvares** [mergentlabs/mergent-js#127]
For testing and debugging purposes, there could be a manual invocation button in the task details view!

**Comment by jamescmartinez** [comment]
Agreed! I'm working on a major backend update in preparation for open-sourcing Mergent, at which point there will be much more progress on the frontend. 

I'm going to keep this issue open to track the status of your request since it's one of the most highly requested features.

**Comment by jamescmartinez** [comment]
@jgtvares This was completed in 0a57dbcd288dbfb6bf9fbb49d43aa6cba3b8bcae and published in 1.3.0.

For reference, the underlying API is now public and [documented here](https://api.mergent.co/docs) as "Run Task"; you can also do the same thing from the dashboard:

![2022-11-03 12 07 34](https://user-images.githubusercontent.com/1286597/199792984-90911031-ec24-4b44-88f1-03debf153a42.gif)

Thanks for your patience on this! I completely forgot about this until you pinged me in Discord to remind me. 😄
