### ISSUE TITLE
[Misleading Docs] Tasks can be searched by name

### ISSUE THREAD

**Issue by jgtvares** [mergentlabs/mergent-js#130]
## Explaining my scenario
In order to easily update tasks (delete and re-create, since an actual update is not available for tasks that were already executed), I'm saving their info in my app database, info like task `id` and `name`.
But I'm starting to think this is not necessary, since Mergent is the actual source of task data I shouldn't add another layer to that, I should trust Mergent's database (I would like to know if you also agree with that).
So, I'm working on removing the logic where my app saves task data in my database.

## The problem - misleading docs
Since the `delete` method requires a task id, I was searching the API docs for an endpoint that I could use to retrieve task data by name. The `List / Search Tasks` method seemed to do the job, but there's no reference that tasks can be searched by name, only `id`, `scheduled_for`, and `created_at` are possible parameters (besides `cursor` which is just for pagination).

## Happy ending
Looking at the `List / Search Schedules`, the `name` parameter has a description indicating that the task id can also be used as a `name`. Then I thought: "Why not try to use the task name as the `id` parameter?".
To my surprise, it worked!
So yeah, you can search tasks by name although the docs have no reference to that.

## Solution
Docs should be clearer about this, 'cause there could be other users looking for this feature.

**Comment by jamescmartinez** [comment]
> Mergent is the actual source of task data I shouldn't add another layer to that, I should trust Mergent's database (I would like to know if you also agree with that)

I agree! We've spent a lot of time making sure that Mergent is incredibly reliable (some behind-the-scenes details: https://twitter.com/jamescmartinez/status/1573782824997511172 & https://twitter.com/jamescmartinez/status/1557030400815423489)

> Docs should be clearer about this, 'cause there could be other users looking for this feature.

You're so right! I'm glad this did what you expected, even though the docs weren't clear. I'll update the docs to note that a Task's `name` will work anywhere `id` works.

Thank you, @jgtvares!

**Comment by jgtvares** [comment]
@jamescmartinez Thanks!!! You're always helpful!
