### ISSUE TITLE
[Help Needed] Next.js-specific version of mergent-js

### ISSUE THREAD

**Issue by jamescmartinez** [mergentlabs/mergent-js#158]
⬇️⬇️⬇️

> This post has been updated. See the most recent update here: https://github.com/mergentlabs/mergent-js/issues/158#issuecomment-1281666254

⬆️⬆️⬆️

I'm looking for feedback on a Next.js-specific part of our library that's being built. I don't write a lot of JS/TS, so I need all the help I can get.

**Context:** Mergent provides APIs for background tasks, and this update wraps our API to make creating background tasks from Next.js easier.

This is what it looks like to use in your Next.js app:

1. Define your background task as an API route. Below I use `/pages/api/tasks/log.js`:

        ```
        import { Task } from "mergent/next";

        export default Task("api/tasks/log", ({ data }) => {
          console.log(`Received: ${data}`); // Do whatever you'd like here
        });
        ```
1. Enqueue the task from a server-side function. This can be another API route or even `getServerSideProps`. Below I use another API route at `/pages/api/tasks/log.enqueue.js`:

        ```
        import log from "./log";

        export default async (req, res) => {
          const task = await log.enqueue("Hello, world!");
        
          res.status(200).send(`Task ${task.id} has been enqueued successfully. 🎊`);
        };
        ```
    This can be called from the frontend with `await fetch("/api/tasks/log.enqueue");`.

1. Start your server with `MERGENT_API_KEY` set to your api key, and `BASE_URL` set to the URL for your Next.js app. 

    In development, I use `ngrok http 3000` to get a base URL. You can start your server with `MERGENT_API_KEY=your_api_key BASE_URL=https://your_ngrok_url npm run dev`. Of course, you can also use `dotenv` or similar so that you don't need to write out that command every time.

That's it! Here's what it looks like in the end: 

![](https://i.imgur.com/g8cIL6c.gif)

**Some specific areas I'd like help with:**

* In step 1, you have to define your API route so we can build an absolute URL for your API. This seems duplicative, given that Next.js uses the file path. Any ideas to get this automatically?
* In step 2, I don't love that you need to create a second endpoint to enqueue the task. Unfortunately, you can't enqueue a task directly from the frontend without leaking API keys, which is why I implemented it this way.
    
    I've thought of making the task API route itself do double duty by detecting the origin of the request (i.e., did the request from the Next.js frontend, or did it come from Mergent's API?). Any suggestions?

**Links:**

* Full Next.js Example: https://github.com/mergentlabs/mergent-js/tree/main/examples/next
* Source for `Task` and `Task.enqueue`: https://github.com/mergentlabs/mergent-js/blob/main/src/next/index.ts
* Mergent's homepage to get an API key: https://mergent.co

Thanks a ton in advance!

James

**Comment by rattrayalex** [comment]
Few thoughts if helpful (take with a grain of thought as I do very little NextJS work):

1. I would ask the NextJS team in discord, twitter, or similar if there's an API to get that endpoint from within the file. At a minimum, I imagine you could get it from the request/context object?
2. I think it's normal and fine to have to reimplement an "enqueue task" endpoint on the backend, personally. Not really a bad thing, since it lets you do your own logging and permissions and stuff as well.
3. I might call it `taskHandler(url, handler)` instead of `Task(url, handler)` in the first example, just an aside. Not sure if the Next community has a better sense of naming convention there.

**Comment by jamescmartinez** [comment]
Thanks, @rattrayalex!

I reached out to the Next.js team for feedback late last week. I'll post back here with an update.

> 3. I might call it `taskHandler(url, handler)` instead of `Task(url, handler)` in the first example, just an aside. Not sure if the Next community has a better sense of naming convention there.

Agreed. I like `taskHandler` much better. I'll change this.

**Comment by KeKs0r** [comment]
I mainly can support al the good talking point from @rattrayalex 

1. It actually possible, the route is on the request object, so providing it in an additional parameter is redundant.
2. I would probably be fine with a default implementation if there is some "built in" security. Like the body of the message hashed with a secret or something to make sure no one else can call the endpoint.
3. I also prefer taskhandler

Additional
I would hope that task is a generic so that I get type completion from the handler into the `enqueue` call.

**Comment by jamescmartinez** [comment]
Thanks, @KeKs0r!

> 2. I would probably be fine with a default implementation if there is some "built in" security. Like the body of the message hashed with a secret or something to make sure no one else can call the endpoint.

Agreed! Though we have support for [validating that the incoming request came from Mergent](https://docs.mergent.co/tasks/webhooks-security#validating-origin-signatures), I couldn't automatically run it in for every request due to a [constraint of Next.js](https://github.com/vercel/next.js/discussions/13405). There are more details in a [comment](https://github.com/mergentlabs/mergent-js/blob/main/src/next/index.ts#L65), but tl;dr: if we did this automatically, we'd have to require everyone to disable `bodyParser` for every task:

```
export const config = {
  api: {
    bodyParser: false,
  }
}
```

I spent a ton of time trying to work around this by parsing JSON back to a string, but I couldn't get it to work in all cases I tried (e.g., `""` and `"{"` and `"{}"` all look different when going from JSON -> string that does not match the _actual_ body string). If you have any ideas, I'm all ears! 👂

> I would hope that task is a generic so that I get type completion from the handler into the enqueue call.

This is a great idea! I can add this.

**Comment by KeKs0r** [comment]
`if we did this automatically, we'd have to require everyone to disable bodyParser for every task:`
I think it would not be that bad, if you disabled the body parser for the user. As long as the callback of the task gets the parsed body:

```
const MyTask = Task(({ data }) => {
  console.log("Data is again the parsed json" , data) 
})

export default MyTask.handler
// This is the part I actually dont like, but dont have a better idea:
export const config = MyTask.config
```

Idea is basically you disable the bodyParser on the level of next, but parse the request again in your task function. You could also add an optional "option" as second argument to Task, which disables that behaviour.

**Comment by jamescmartinez** [comment]
Interesting idea! Definitely worth exploring.

I'm going to play around with this option today/tonight and post back tomorrow.

**Comment by jamescmartinez** [comment]
After some more exploration with two developers in a call an hour or so ago, I've decided to hold off on creating a Next.js-specific wrapper _**for tomorrow's 1.1 release**._ 

In short, I want to ensure this API is "idiomatic" for Next.js developers before we ship it. I'll be reaching out to @leerob from Vercel for additional feedback in the morning since there's a good chance we're missing something that could make this even better.

I'll continue posting updates in this issue as Mergent's Next.js API evolves.

### New 1.1 Release Tomorrow

Two improvements will be released to `npm` tomorrow: `delay: Duration` and `scheduledFor: Date`. These improvements were inspired by the changes initially created for Next.js, so thank you all for testing and providing feedback.

I'll write up more docs before shipping to `npm` but in the meantime, here is what those changes look like:

####  Delay
It's now easier to delay tasks without learning/using ISO 8601 Durations directly. This is a backward-compatible change.

```js
// Before
mergent.tasks.create({ request: { url: "..." }, delay: "PT5M" });
// Upcoming 1.1
mergent.tasks.create({ request: { url: "..." }, delay: { minutes: 5 }});
```

#### Scheduled For
You can now use `Date` instead of an ISO 8601 string to schedule a task with the `scheduledFor` param.

This change also deprecates the _snake_cased_ `scheduled_for` param in favor of a more idiomatic _camelCased_  `scheduledFor`.

```js
// Before
mergent.tasks.create({ request: { url: "..." }, scheduled_for: "2022-10-17T22:28:17.615Z" });
// Upcoming 1.1
mergent.tasks.create({ request: { url: "..." }, scheduledFor: new Date() });
```
