### ISSUE TITLE
Task name does not display in dashboard simple view

### ISSUE THREAD

**Issue by jgtvares** [mergentlabs/mergent-js#69]
I'm sure this is not the correct place for this issue, but I didn't find the frontend project, so here it goes!

When I create named tasks, the name does not show easily in the dashboard, only when you expand the `Details`.
It would be really nice to have the task name visible in the dashboard.
In my app, the user can create multiple scheduled routines, so seeing the tasks' names would help a lot with finding and debugging a specific task in a big list.

I can propose two solutions:
1. If the task has a name, then the name is displayed in the `Task` column;
2. Add a new column called `Task Name` and rename the `Task` column to `Task ID`;

I would happily contribute if possible!

**Comment by jamescmartinez** [comment]
Hey @jgtvares! Thanks for this feedback; it seems like a perfectly reasonable thing that should be shown in the task list. I'll add it to my todo list for this week and post back here with an update once it's live.

Also, you're right -- the frontend project isn't open-source. I've had it on my list for a while to scrub the repo to ensure there isn't anything in there that we don't want to be public. Once I do that, we'll open source it.

**Comment by jamescmartinez** [comment]
@jgtvares -- It's live. 🎊

**Comment by jgtvares** [comment]
> @jgtvares -- It's live. 🎊

It is not working for me 😢 
I'm still seeing the old view:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/47645535/166306260-98432131-f727-4e2a-8af8-497ee60bebdf.png">
