### ISSUE TITLE
Tasks are executed as soon as they're created

### ISSUE THREAD

**Issue by jgtvares** [mergentlabs/mergent-js#71]
When I create a task it is executed right away, ignoring the `scheduledFor` parameter sent in the request.
It does not happen when creating tasks via the web interface or requesting the API directly.

**Comment by jamescmartinez** [comment]
Hi @jgtvares -- can you email support@mergent.co with the Task details/params? We'll dig through logs and take a look to see what's going on. Thanks!

**Comment by jgtvares** [comment]
> Hi @jgtvares -- can you email support@mergent.co with the Task details/params? We'll dig through logs and take a look to see what's going on. Thanks!

I have already deleted the task, but I'll send it anyway. Thank you for responding!

**Comment by jamescmartinez** [comment]
Closing since we're now chatting via email.
