### ISSUE TITLE
Buggy page refreshes

### ISSUE THREAD

**Issue by jgtvares** [mergentlabs/mergent-js#76]
I have two projects in Mergent. I'll call them **P1** and **P2**.
When refreshing the Tasks page in **P1**, for example, I'm redirected to the same page but in **P2**.
So, I have to change the project on every refresh.

**Comment by jamescmartinez** [comment]
Hey @jgtvares - thanks for opening this issue. We now remember the selected project across refreshes in the dashboard.

**Comment by jgtvares** [comment]
Thanks @jamescmartinez!!!
